
title: 永烁星光之地
author:
  name: 王海明
  email: 11178243@qq.com
description: 枯坐到清晨 阳光替房间开了灯

theme: minima


defaults:
  -
    scope:
      path: ""
      type: "posts" 
    values:
      layout: "post"

minima:
  social_links:
    github:  HmingWang